[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_bazaar = "DsSEEH3fuQ3keMZkWiz28yGVDW6VADbqW3ryhe816g1b"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
